#Admin configuration
info:
  name: @app.id@
  description: @app.id@
  version: @pom.version@
  stage: local

spring:
  application:
    id: @app.id@
    name: @app.id@
  boot:
    admin:
      client:
        url: ${boot.admin.client.url}
        username: ${boot.admin.client.username}
        password: ${boot.admin.client.password}

easyms:
  logging:
    logstash: # Forward logs to logstash over a socket, used by LoggingConfig
      enabled: false
      host: "localhost"
      port: 5000
      queue-size: 512